### ISSUE TITLE
Sometime downloading will receive a TypeError

### ISSUE THREAD

**Issue by xin344** [RoyShen12/pornhub-downloader#3]
Like this:
TypeError: Cannot read property 'title' of undefined
    at Object.downloadVideo (C:\softs\nodejs\pornhub-downloader-master\src\lib\scrapy.js:318:23)
    at run (C:\softs\nodejs\pornhub-downloader-master\src\index.js:208:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by xin344** [comment]
but re-start the downloading sometime it turns to be usual, why this?
Thank you!

**Comment by RoyShen12** [comment]
I will check this soon :)

**Comment by RoyShen12** [comment]
Did that only happened when running with --key flag?

**Comment by xin344** [comment]
Yea, it happened with -k flag, but I didn't test other flags.

**Comment by RoyShen12** [comment]
I just fixed this issue, it shouldn't happen again :)
